# authorization by email address
mail:
  debug: true
spring:
  mail:
    port: 587
    password: 5897121994g
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    username: tulaa478@gmail.com
    host: smtp.gmail.com
  main:
    allow-bean-definition-overriding: true

  datasource:
    hikari:
      connection-timeout: 60000
    password: 5897121994g
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    open-in-view: true
    properties:
      hibernate:
        default_schema: converter
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 100000
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
